### ISSUE TITLE
Requires SQLite 3.8.3 or higher

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [aws/aws-elastic-beanstalk-cli#100]
Dear there,

I am using:
- Django==3.2.8, 
- Python==3.8.5  
- Pip==21.3.1

After deployment, when I try to connect with admin account I get this error :
![x](https://user-images.githubusercontent.com/74948380/145259985-c20b1132-aa3e-4e0d-a7db-3385f5142cfa.png)

What should I do ?

**Comment by NihalM99** [comment]
Hi @MedNabilEssefaihi Can you please share more info , with repro steps.

**Comment by jsheld** [comment]
Unless there is more specific information, we are unable to continue looking into this issue. If you choose to reopen it, please provide more information. From what I can tell, this appears to be an issue with the web site you deployed, not explicitly with the eb cli.

**Comment by MedNabilEssefaihi** [comment]
Hello @jsheld @NihalM99 

First, I would like to thank you for response,
This issue had submit about 2 years ago. Which makes no sense to your question, now.

Thank you.
