### ISSUE TITLE
Allow latest version of botocore

### ISSUE THREAD

**Issue by zags** [aws/aws-elastic-beanstalk-cli#101]
## Community Note

Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request. Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request. If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Tell us about your request
Please expand the range of botocore versions that the eb-cli is compatible with to include the latest version of botocore (1.23).

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
The eb-cli currently requires `'botocore>=1.21.0,<1.22.0'`.  This tight range on botocore is fairly limiting for compatibility with other libraries.  In particular, this library is incompatible with the current version of the [aws-cli](https://github.com/aws/aws-cli), which depends on `'botocore==1.23.31'`. 

### Are you currently working around this issue?
Yes

### How are you currently solving this problem?
This requires the different CLIs into different virtual environments, such as doing one CLI as a global install and the other in the project virtual environment.  This is challenging for onboarding new developers.

**Comment by joshfriend** [comment]
The overly tight pinning of dependency versions in aws python command line tools is absurd. There are **zero versions** of `awsebcli` that can be installed alongside `awscli` using a tool that checks dependency conflicts (poetry).

**Comment by Mickeypeng** [comment]
Hi zags@ thanks for reaching out. We just updated the botocore version as you requested. For future reference, we recommend our customer to use the EB CLI install script which install EB CLI into a python virtual environment in order to avoid such version conflict with AWS CLI. EB CLI install script repository is here: https://github.com/aws/aws-elastic-beanstalk-cli-setup. We are also working on a new path forward to update package version in time.

**Comment by joshfriend** [comment]
`>1.23.41,<1.24.0` is still an extremely narrow range. It was updated recently with commit 4c2fe06026da45e226994e9e5b6904fa88c51d73 which said: `Update CHANGES.rst and increment version to 3.20.3`. No explanation of why the minimum version increase makes a difference for the EB CLI.

It's also not just botocore, it's other dependencies too. `six` (#85, #38, #61), `PyYAML` (#5, #6), for example both have an excessively narrow version spec that prevents it from being installed along other tools like awscli or aws-sam-cli.

**Comment by joshfriend** [comment]
I can understand the need to avoid version specs that are too loose where you might accidentally resolve a dependency that is too old/new and causes things to not work. however in those cases, an end user can pin the problematic versions on their app's side.

When package dependency versions conflict with each other, poetry/pipenv will just not let you install them at all and you don't really have any recourse besides developing an entirely separate install process for these tools.
