### ISSUE TITLE
Bump pathspec from 0.5.9 to 0.9.0

### ISSUE THREAD

**Issue by giuliano-oliveira** [aws/aws-elastic-beanstalk-cli#103]
## Community Note

Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request. Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request. If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Tell us about your request
Currently awsebcli is using pathspec version 0.5.9 that were released in 2018-09-15, and the latest is 0.9.0.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
This  outdated dependency is problematic because for example black version 21.12b0 uses pathspec>=0.9.0, making impossible to install the latest black and awsebcli in the same virtual environment.

### Are you currently working around this issue?
yes

### How are you currently solving this problem?
Installing black or awsebcli in separated environments, one in venv and the other in the system

**Comment by marns93** [comment]
@Mickeypeng Can you please have a look on it? :)

**Comment by Mickeypeng** [comment]
Hi giuliano-oliveria@ thanks for reaching out. We just updated the pathspec version to 0.9.0 and pushed to github as you requested.
