### ISSUE TITLE
Environment variables removed when deploying

### ISSUE THREAD

**Issue by jcw-** [aws/aws-elastic-beanstalk-cli#12]
### Description

Deploying clears a previously set environment variable.
- I am using an `env.yml` but it does not contain a section for environment variables

I have tried:
- specifying the env var on the create step using `--envvar`, but this seems to have no effect, no env var is made
- adding an env var to `env.yml` and then trying to get it overridden during create using `--envvar`, again, the parameter has no effect, and the value in `env.yml` gets set

**Why don't I simply just put my env var details into `env.yml` if that is working?**
Because I create and deploy both a staging and a production environment for each module, and I need to set a different value for the env var.

**Why don't I simply script a `deploy` followed by a `setenv` and call it a day?**
Because this results in downtime!

### Steps to reproduce

1. `eb create --modules priority-score-calculator --env-group-suffix staging`
1. `cd priority-score-calculator`
1. `eb setenv NODE_ENV=staging -e priority-score-staging`
1. `cd ..`
1. `eb deploy --modules priority-score-calculator --env-group-suffix staging`

### Observed result

The env var set through `setenv` gets blitzed by the `deploy` command.

### Expected result

Tthe env var set through `setenv` is not modified by the `deploy`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. EB CLI - installed via brew: `EB CLI 3.17.0 (Python 3.8.1)`

**Comment by halcarleton** [comment]
Hi @jcw-,

Thanks for reaching out. After some investigating I do see that the `--envvars` option is not currently supported when running `eb create` with the `--modules` option. I don't see any mention of this in the documentation though, so I will look into either updating the docs or modifying the behavior for that option.

As far as eb deploy removing environment variables, I have attempted to reproduce this issue and have not seen any irregularity in environment variables during `eb deploy` or `eb setenv`. 

Could you provided more details about how you are verifying whether or not an environment variable is set?

Thanks

**Comment by jcw-** [comment]
> Could you provided more details about how you are verifying whether or not an environment variable is set?

I'm looking for it in the EB web console. I can set it there or through `eb setenv` and either way it disappears on the next `eb deploy`. Note that I do not have any env vars defined in env.yml.

**Comment by halcarleton** [comment]
Interesting, I am following your repro steps and am not seeing the same behavior.

Are there any environment properties set after you complete a deploy or are all environment properties removed? If there are environment properties set could you find how/where they are configured?

Additionally, if possible, could you provide an example application codebase that reproduces these issues and share that here(either a zip or a repo link)?

**Comment by jcw-** [comment]
> Are there any environment properties set after you complete a deploy or are all environment properties removed? 
Well, I'm actually only dealing with one env var - I haven't tried setting a second one and seeing if it is also removed by the deplay, would that be a useful experiment?

I'm weighing the time to create a sanitized repro case vs doing a live demo - is that an option? If so, is there an EB or some AWS Slack workspace I can join?

**Comment by halcarleton** [comment]
Ok, I was able to reproduce the issue. If I am understanding correctly, you _do not_ define any environment properties in your env.yml, but you _do_ define option settings. It appears that the Elastic Beanstalk service is removing your environment variables, which means this is not an EB CLI bug. I would recommend reporting this on the [AWS Elastic Beanstalk forum](https://forums.aws.amazon.com/forum.jspa?forumID=86).

You should be able to reproduce the issue with the awscli by running the following command instead of `eb deploy` in your repro steps:

```
aws elasticbeanstalk compose-environments --application-name <application_name> --group-name <group_name> --version-labels <latest_appliction_version_label>
```

A workaround you could try in the meantime is to define your option settings in `.ebextensions` instead of in your `env.yml`. More info on that [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions.html).

**Comment by jcw-** [comment]
>  If I am understanding correctly, you do not define any environment properties in your env.yml, but you do define option settings. 

Correct - thanks for narrowing it down, I'll submit an issue on the other forum.

Also thanks for the option settings in `.ebextensions` tip, I'll try that.
