### ISSUE TITLE
Deleted app folders reappear on elastic beanstalk cluster after eb deploy

### ISSUE THREAD

**Issue by nsamarak** [aws/aws-elastic-beanstalk-cli#20]
I have my source code checked into git and run eb deploy to push the latest code to my eb cluster. There's a bug in the eb deploy command that causes a folder that was previously deleted to show up in my eb cluster after running eb deploy. The deleted folder is <APP_ROOT>/node_modules/i18n/node_modules.

This folder does not exist in git. It does not exist in the archive that is created at <APP_ROOT>/.elasticbeanstalk/app_versions by eb deploy. However, it does exist by the time eb deploy copies code to /tmp/deployment/application on the eb cluster.

eb deploy should not manifest any folders or files under /var/app/current that does not exist in the archive initially created at <APP_ROOT>/.elasticbeanstalk/app_versions.

I'm using EB CLI 3.17.1 (Python 3.8.2). The debug output of eb deploy is at [eb_deploy_log.txt](https://github.com/aws/aws-elastic-beanstalk-cli/files/4372287/eb_deploy_log.txt)

**Comment by rahulrajaram** [comment]
@nsamarak , can you confirm you're indeed talking about `node_modules/i18n/node_modules` and not `node_modules/@ladjs/i18n/node_modules`? `eb deploy` is not uploading the first one.

**Comment by nsamarak** [comment]
I am only talking about node_modules/i18n/node_modules.

**Comment by rahulrajaram** [comment]
Thanks for confirming. From the logs you've posted, I don't see that directory being uploaded, so this is not a EBCLI problem. To confirm, you can download the application version that your EC2 instances are running from S3, and check it's contents. There's also a `eb labs download` that can download the current application version. Another thing to check is whether your newer deployments (ones without the above directory) are actually successful. If they've failed, it would explain why you still have the directory on the instances.

**Comment by nsamarak** [comment]
The newer deployment show up under /var/app/current so that's not the issue. 

The eb deploy command is responsible for copying the temporary archive at .elasticbeanstalk/app_versions to /tmp/deployment/application on the eb cluster. Since the issue manifests between those 2 points, what else would be responsible if not for eb deploy?

**Comment by rahulrajaram** [comment]
I looked up your recent deployments in the backend, and I can't determine what the problem is. Can you run `eb logs download`, unzip the contents, and see if `node_modules/i18n/node_modules` exists in it? It it does not, it would be an indication that the problem is not with the EBCLI.

I am also curious if there are any commands in your `.ebextensions/030.node.config` file.

> The eb deploy command is responsible for copying the temporary archive at .elasticbeanstalk/app_versions

Correct, although it is slightly more complicated. `eb` merely hands off your code to the EB service.

When you perform `eb deploy`, the EBCLI/`eb`:
    1. uploads the temporary file in `.elasticbeanstalk/app_versions` to S3
    2. invokes the Beanstalk API call, `CreateApplicationVersion` while pointing to the above S3 location
    3. invokes the Beanstalk API call, `UpdateEnvironment` using the "application version" created in `2.`

> Since the issue manifests between those 2 points, what else would be responsible if not for eb deploy?

Possibly a bug in the EB service, but it's too soon to tell.

**Comment by nsamarak** [comment]
Thanks for the explanation!

I ran `eb logs <MY_ENV_NAME>` and there's no mention of node_modules in there. However the logs also don't go to the level of calling out each of the files of the deployment.

030.node.config just has npm start.

Regarding your step (1), the zip file that exists in s3 does not have the node_modules/i18n/node_modules folder.

Something else to note -- I can delete /var/app/current/node_modules/i18n/node_modules, but as soon as I do a deployment, this folder reappears.

[.ebextensions/030.node.config](https://github.com/aws/aws-elastic-beanstalk-cli/files/4378738/030.node.config.txt) and the [output of eb logs](https://github.com/aws/aws-elastic-beanstalk-cli/files/4378743/eblogs.txt) are attached.

**Comment by rahulrajaram** [comment]
Sorry, I meant `eb labs download` not `logs`. I've edited my comment. This command basically does the same thing automatically that you did manually (download file from S3). So sounds like the directory in question is not uploaded in the first place.

> Something else to note -- I can delete /var/app/current/node_modules/i18n/node_modules, but as soon as I do a deployment, this folder reappears.

After a deployment, EB runs scripts on the EC2 instances. `npm install` may be run under particular conditions. I suspect that is what is recreating the nested `node_modules` dir. Can you not remove the `i18n` dir?

**Comment by nsamarak** [comment]
I can remove the directory after running eb deploy. That feels like a bandaid though. Is there a way to prevent npm install from running?

**Comment by rahulrajaram** [comment]
> I can remove the directory after running eb deploy.

No, you shouldn't have to do this.

I am wondering whether you can put `node_modules/i18n` inside a top-level `vendor` directory, or inside a `lib/vendor`. That way you still have access to `i18n`'s source code. Basically, you'll have a `vendor/i18n` or a `lib/vendor/i18n` 

Alternately, you can try commenting out the "`dependencies`" attribute in `node_modules/i18n/package.json`, making `npm install` a no-op.

**Comment by nsamarak** [comment]
Since I only want to run npm install on dev, I renamed dependencies in package.json to devDependencies and that prevents npm from installing packages on production since ebnode.py sets the production flag.

Thanks for working through this!
