### ISSUE TITLE
eb init with --modules ignores provided application name

### ISSUE THREAD

**Issue by Elywejnak** [aws/aws-elastic-beanstalk-cli#225]
### Description
Trying to initialize multiple folders at once with: 
` eb init appname --region eu-west-2 --platform "docker" --keyname aws-eb-appname --modules server worker`

which results in initialized folders, but instead of using application **appname** it creates a new el. beanstalk application based on name of root folder (in our case it's folder **deployment**). 

(from quick look into code it seems to be because of this line https://github.com/aws/aws-elastic-beanstalk-cli/blob/b062bafa96ee5a64289ceac7783f6d6bf6ed957f/ebcli/controllers/initialize.py#L137 which initializes app_name as None and the same variable is then used without change just few lines below to detect the name)

### Observed result

Initializes folders with wrong application

### Expected result

Initializes folders with provided application 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu
2. EBCLI version: EB CLI 3.20.3 (Python 3.8.1)

**Comment by yohanthshetty** [comment]
Hi @Elywejnak , You have correctly pointed out the bug. Any inconvenience caused is regretted. This issue has been fixed in the latest version. You can pull the latest code to update.
Closing this issue for now.
