### ISSUE TITLE
Allow uploading application version without deployment to environment

### ISSUE THREAD

**Issue by alexjurkiewicz** [aws/aws-elastic-beanstalk-cli#29]
### Tell us about your request

In our CI system, I would like to build and upload application versions. I don't want to commit my .eb configuration, I just want to run a command like `eb deploy --application MyApp --label "$GIT_SHA" --description "$GIT_COMMIT_MSG"`.

Currently, the file `.elasticbeanstalk/config.yml` has to exist, and there's no way to say "just upload the build, don't deploy it to an environment".

### Are you currently working around this issue?

Building and uploading app version with a standalone shell script using aws cli.

### Additional context

I would be happy to work on this, but I think some architectural decisions have to be made:
* Will this FR be accepted
* How to implement commands which don't require `eb init`

**Comment by halcarleton** [comment]
Thanks for the input @alexjurkiewicz.

So if I am understanding correctly, you have two main requests here:

**1. Build and upload an application version without deploying it to an environment**

First, you are correct, there is currently no way to build and upload an application version without also deploying it to an environment using the EBCLI. This is something we could likely add support for. I would like to better understand the use-case first though. Could you expand on what your workflow is and why you need/want to upload application versions without deploying them?

**2. Run `eb` commands on a directory that has not been initialized**

I'm not quite understanding why this would be necessary for your use-case. Could you expand on why it is undesirable for you to first initialize the directory before performing other actions?

While it would be possible to remove that restriction it would be contrary to the intended workflow that the EBCLI is designed around. We would need a good reason extend the design to include support for uninitialized directories.

Thanks!

**Comment by alexjurkiewicz** [comment]
Hi Hal. In our test infrastructure we dynamically create EB environments
for developers to deploy their code to for testing. The process is like
this:

1. Developer pushes code to codecommit repo
2. Codepipeline runs ci for the branch which passes
3. Developer uses an internal tool to trigger a "test deploy" task.
4. This task builds the EB app ver, uploads it to a fixed application, then
creates a new EB environment in that application using the app ver
5. Developer can now test their code in a prod-like environment

So there are a few points which don't match the workflow ebcli assumes. In
fact, developers generally only use the tool to easily ssh to environments.

Step 4 is what I'd like ebcli to help us with. Currently we use a custom in
house tool to zip up the application while respecting ebignore. It would be
easier if we could use ebcli and throw away this custom tooling.

About supporting execution without initialisation. As far as I know, it's
not possible to initialise ebcli in a noninteractive way. That means to use
it in a CI tool we would have to do something hacky. Am I mistaken?

**Comment by halcarleton** [comment]
> 4. This task builds the EB app ver, uploads it to a fixed application, then
creates a new EB environment in that application using the app ver

I see, so you are creating a new environment. In that case what you really want is to run `eb create`, this will build and upload an application version for you then create a new environment with that application version. 

The one caveat with this solution is that `eb create` does not currently support defining the application version label. This is something we should be able to address in the future.

> About supporting execution without initialisation. As far as I know, it's
not possible to initialise ebcli in a noninteractive way. That means to use
it in a CI tool we would have to do something hacky. Am I mistaken?

So, you are able to run `eb init` without interactive prompts, unfortunately it is currently not terribly intuitive so it's easy to miss. This is something we would like to address in the future.

In order to run `eb init` without interactive prompts you just need to make sure you provide the `--platform` option.

**Comment by alexjurkiewicz** [comment]
Thanks for the response.

> I see, so you are creating a new environment. In that case what you really want is to run eb create, this will build and upload an application version for you then create a new environment with that application version.

Currently, we create environments with CloudFormation. `eb create` was considered, but we've avoided it as it (seems to be) imperative. With CF, we declare the final state of the environment and it will handle either creating a new environment or updating an existing one.

Our applications also require a lot of auxiliary AWS resources. Such as SNS topics, SSM parameters, etc. We manage these with CF anyway, so it makes sense to do the same for EB resources whenever possible.

I guess you can say we've ejected from the blessed eb cli workflow :)

> In order to run eb init without interactive prompts you just need to make sure you provide the --platform option.

Excellent! Thanks for the tip.

I have updated the thread title to reflect our amended request. We can now initialise non-interactively, so we'd just like the ability to upload app versions without deploying them.

**Comment by halcarleton** [comment]
Gotcha, well it seems reasonable to me to want to create an application version outside of a deploy/create action. Especially because this is functionality that is supported in the AWS EB console.

I will leave this open while we review adding this to our roadmap.

**Comment by orestis** [comment]
Just chipping in here, we have a similar requirement with a different use case:

* We want to be able to easily deploy any "green" branch (e.g. branches that pass all CI tests)
* But we don't want to immediately deploy when tests pass, just do all the pre-compilation etc and upload the build artifact somewhere (this could be S3 or something similar)
* Then when we are ready to go, we can point to a pre-built artifact and deploy, which means we don't have to go through building everything again. 

Being able to generate and upload an artefact that's ready for deployment would allow this workflow.

**Comment by antgel** [comment]
Our use case for this useful feature:

* We have two EB environments, one for serving the webapp, one for background jobs (using Sidekiq, not worker tier)
* When we deploy, it's the same source code bundle that goes to both, we know whether to start Puma web server or Sidekiq based on an environment variable and predeploy platform hook that copies the right Procfile into the actual `Procfile`.

**Comment by Mickeypeng** [comment]
Hello everyone, thanks for requesting this new feature. I am glad to say that creating application versions without deployment is now available by --create option in eb appversion command in our new version(3.20.0) cli. See documents for eb appversion command for detailed usage.
