### ISSUE TITLE
awsebcli fails to install through pip

### ISSUE THREAD

**Issue by yuriploc** [aws/aws-elastic-beanstalk-cli#327]
### Description

Trying to install `awsebcli` from pip.

### Steps to reproduce

```sh
$ python --version
Python 3.10.5

$ pip --version 
pip 22.0.4 from .asdf/installs/python/3.10.5/lib/python3.10/site-packages/pip (python 3.10)

$ pip install awsebcli
Collecting awsebcli
  Using cached awsebcli-3.20.4.tar.gz (260 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xk26uo_e/awsebcli_685f68d9c1994eec8fcfa2f7b0c463b8/setup.py", line 22, in <module>
          with open("requirements.txt") as req:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the '.asdf/installs/python/3.10.5/bin/python3.10 -m pip install --upgrade pip' command.
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux 6.1.10-200.fc37.x86_64
2. EBCLI version: 3.20.4 (2023-02-27)

**Comment by yuriploc** [comment]
This also fails in CircleCI running `ubuntu-2004:202111-01`

**Comment by willywu** [comment]
It looks like this is breaking https://circleci.com/developer/orbs/orb/circleci/aws-elastic-beanstalk (which performs `pipx install awsebcli`), preventing any EB deployments through CircleCI.  Thoughts on yanking the most recent awsebcli package release?

**Comment by timbrownsf** [comment]
Happening for us as well.

**Comment by ikegentz** [comment]
We are experiencing the same issue, but it is resolved by specifying the earlier version:

```
pipx install awsebcli==3.20.3
```

**Comment by yuriploc** [comment]
As @kirillrdy pointed out [here](https://github.com/aws/aws-elastic-beanstalk-cli/pull/329#issuecomment-1449021417), the `requirements.txt` is not present in pip.

**Comment by JosephUrciuoli** [comment]
+1 - also seeing this issue. Error details on Circle CI

`PIP STDOUT
----------
Collecting awsebcli
Downloading awsebcli-3.20.4.tar.gz (260 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 260.7/260.7 kB 5.3 MB/s eta 0:00:00
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'

PIP STDERR
----------
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/tmp/pip-install-9i16_ygi/awsebcli_4c8605696a4d48b990ba577d252b73f8/setup.py", line 22, in <module>
with open("requirements.txt") as req:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by kirillrdy** [comment]
https://github.com/aws/aws-elastic-beanstalk-cli/pull/330

**Comment by yuriploc** [comment]
Closing as resolved by https://github.com/aws/aws-elastic-beanstalk-cli/pull/330.
