### ISSUE TITLE
Consider updating restrictive max-version dependencies (e.g. six, future, requests)

### ISSUE THREAD

**Issue by ibushong** [aws/aws-elastic-beanstalk-cli#38]
## Community Note

Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request. Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request. If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Tell us about your request
**I constantly struggle with keeping my requirements file free of dependency conflicts due to some of the version requirements imposed by `awsebcli`**, namely `six`, `requests` and `future` seem to be the biggest offenders.

`awsebcli` v3.18.1 requires:
- `future>=0.16.0,<0.17.0`
  - `future` v0.17.0 was released October 2018
- `requests>=2.20.1,<2.21`
  - `requests` v2.21.0 was released December 2018
- `six>=1.11.0,<1.12.0`
  - `six` v1.12.0 was released December 2018

One workaround is just to have a separate environment for using `awsebcli`, but it would be great to get everything working in one env.

I don't know the history/details behind these restrictions, but I would think/hope that they can be improved at least somewhat.

**Comment by halcarleton** [comment]
Thanks for reaching out @ibushong. We will take a look at updating these requirements and post any updates here.

**Comment by piotrsroka** [comment]
I would like to add two more dependancies:
- `botocore>=1.15,<1.16`
  - `botocore` v1.15.49 was released April 2020
- `pathspec==0.5.9`
  - `pathspec` v0.5.9 was released September 2018

 `botocore` v1.15.4 is not a very outdated package, however it's impossible to use it alongside with newest `boto3`. At the time of writing, the newest `boto3` v1.14.37 requires `botocore>=1.17.37,<1.18.0`

**Comment by matschaffer** [comment]
Incase it helps anyone trying to package both boto3 and awsebcli, as of writing this locking to `boto3==1.12.49` seems to resolve botocore incompatibilities.

**Comment by Palakpatel67** [comment]
We have updated dependencies in [EBCLI 3.19.2](https://pypi.org/project/awsebcli/3.19.2/)
We will keep monitoring dependency requirements.

**Comment by eykanal** [comment]
Just to be sure, if there a different place to request updates? `pathspec 0.5.9` is now two years old and is causing conflicts (most recently with `black 20.8b1`).

**Comment by simoroma** [comment]
I still have the same issue with `awscli 3.19.3` when I install `s3fs`:
`awsebcli 3.19.2 requires botocore<1.20.0,>=1.19.0, but you have botocore 1.17.44 which is incompatible.`

**Comment by SafaAlfulaij** [comment]
Can we please update `pathspec` version? It's causing issues with `black` for almost a year now...
```
There are incompatible versions in the resolved dependencies:
  pathspec<1,>=0.9.0 (from black==21.10b0->-r C:\Users\User~1\AppData\Local\Temp\pipenvt585eh4arequirements\pipenv-inunr0b_-constraints.txt (line 8))
  pathspec==0.5.9 (from awsebcli==3.20.2->-r C:\Users\User~1\AppData\Local\Temp\pipenvt585eh4arequirements\pipenv-inunr0b_-constraints.txt (line 5))
```
