### ISSUE TITLE
docker-compose v1 is deprecated

### ISSUE THREAD

**Issue by chenrui333** [aws/aws-elastic-beanstalk-cli#448]
see [this comment](https://github.com/docker/compose/issues/9114#issuecomment-1645331064)

relates to https://github.com/aws/aws-elastic-beanstalk-cli/pull/442

**Comment by petewalker** [comment]
In fact, it's actually [EOL](https://github.com/docker/compose/issues/9114#issuecomment-1645331064). Is it possible to remove the dependency from the package, or make it an `extra`?

This project seems to already require that Docker is installed for some of its commands in any case:

https://github.com/aws/aws-elastic-beanstalk-cli/blob/54abc1e09380c00b67c52b9f89b0c0177fddb519/ebcli/containers/commands.py#L60C1-L61

So, moving `docker compose` to be an external dependency seems reasonable to me?

**Comment by petewalker** [comment]
Hi @NihalM99 - I'm not sure this resolves this issue fully? `docker-compose` is EOL - increasing the version range doesn't really help the problem. The last release for `docker-compose` was over 3 years ago.

As an example of its issues, it places an upper limit on `PyYAML` of `<6`, which can lead to this issue: https://github.com/yaml/pyyaml/issues/724

**Comment by swiffer** [comment]
@petewalker - looks like #464 addresses the issue
