### ISSUE TITLE
`docker-compose` v1 is considered EOL

### ISSUE THREAD

**Issue by petewalker** [aws/aws-elastic-beanstalk-cli#456]
The resolution to https://github.com/aws/aws-elastic-beanstalk-cli/issues/448 simply extended the upper limit of `docker-compose` as a dependency, but as reported by Docker themselves, the package is considered end-of-life by them [^1][^2].

The code hasn't had a release shipped for over 2 years [^3], and its replacement has been written in golang, so it is no longer a python depedency.

Given that `docker` is already an external dependency, would it be possible to remove the `docker-compose` dependency, and simply check whether it is installed before trying to run a relevant command? `docker-compose` is already run as an external executable anyway: https://github.com/aws/aws-elastic-beanstalk-cli/blob/54abc1e09380c00b67c52b9f89b0c0177fddb519/ebcli/containers/commands.py#L116

And it isn't even installed on Windows:
https://github.com/aws/aws-elastic-beanstalk-cli/blob/9351a4420f8ce182c71fd2df6cdffdb4a18475d2/setup.py#L39-L41

It's becoming problematic, because its current dependency upper limits are starting to cause issues with the dependency tree. For example, it places an upper limit on `PyYAML` of <6, which can lead to this issue: https://github.com/yaml/pyyaml/issues/724

[^1]: https://github.com/docker/compose/issues/9114#issuecomment-1645331064
[^2]: https://github.com/docker/compose/tree/master#warning-compose-v1-is-deprecated-warning
[^3]: https://pypi.org/project/docker-compose/#history

**Comment by KamilMroczek** [comment]
+1 to this issue. We are also experiencing this issue.

**Comment by swiffer** [comment]
+1, our docker based ci container no longer builds successfully.

**Comment by NihalM99** [comment]
Merged .
