### ISSUE TITLE
field translation from docker-compose.yml 

### ISSUE THREAD

**Issue by hkbluesky** [aws/aws-elastic-beanstalk-cli#46]
Because the document is really lacking, I have several questions about field translation. Here is my original post:
https://stackoverflow.com/questions/63572956/difficult-fields-from-docker-compose-yml-to-dockerrun-aws-json
Thanks

**Comment by Palakpatel67** [comment]
Hey @hkbluesky, thanks for reaching out. Unfortunately this is not the appropriate venue for EB docker image support. I would recommend posting your issue to the [AWS Elastic Beanstalk forum](https://forums.aws.amazon.com/forum.jspa?forumID=86) for further assistance. Closing as not related to EBCLI.
