### ISSUE TITLE
--staged ignored, eb deploy uploading entire local version

### ISSUE THREAD

**Issue by owurman** [aws/aws-elastic-beanstalk-cli#47]
### Description

When deploying with --staged, eb deploy is uploading my entire local directory rather than just content staged in git.

### Steps to reproduce

Make an obvious change to code, don't stage it, run eb deploy --staged

### Observed result

Change is deployed

### Expected result

Change is not deployed

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 10.15.5
2. EBCLI version: EB CLI 3.18.2 (Python 3.8.5)

**Comment by owurman** [comment]
I tested it several ways:
No files staged
Some other file staged
Same file staged but only certain changes

In each case, the unstaged change would get deployed.

I also thought maybe it was user error because I was putting --staged before my environment name. That made no difference.

**Comment by Palakpatel67** [comment]
@owurman Thanks for reaching out. I’ve so far been unable to reproduce the issue. I have tried it several ways and it was working as expected, so if you don’t stage your changes(run `eb deploy`), changes won’t be deployed and if you staged your changes(run `eb deploy --staged`) it will be deployed with entire local directory content.

Could you provided more details about few use cases? 
What is your observed result when you don't stage your changes and run `eb deploy`?  (Expected result: changes don't get deployed)
What is your observed result when you stage your changes and run `eb deploy --staged`? (Expected result: changes will be deployed)

thanks!

**Comment by owurman** [comment]
Perhaps I'm misunderstanding. If I staged only certain changes/files in git
and run with eb deploy --staged, does it take the *entire local contents*,
not just what is staged?

Regardless, I just tested with changes in local folder, eb deploy
*without* --staged,
and *all local, uncommitted changes* were clearly uploaded. Don't know what
to tell you. This is with EB CLI 3.19.2.

**Comment by Palakpatel67** [comment]
@owurman thanks for confirming. So if you stage certain changes and run `eb deploy --staged` it will deploy newly staged content plus previously committed content (unstaged changes will not be deployed). 

I have attempted to reproduce this issue with EB CLI 3.19.2 and not seeing the same behavior. Could you include an example codebase(github repo or directory archive) which reproduces this issue and exact steps to reproduce?

**Comment by owurman** [comment]
I don't have an example codebase, but I do run under a python venv, perhaps
that's the issue?

**Comment by owurman** [comment]
Nope, same behavior for me when not in the virtual env.

**Comment by Palakpatel67** [comment]
Could you provide exact steps to reproduce this issue?

**Comment by owurman** [comment]
Make a change in the code.
Run eb deploy without --staged.
Change gets deployed, anyway.

I'm really not doing anything special here.

**Comment by Palakpatel67** [comment]
@owurman, I am following your steps and am not seeing the same behavior. Could you provide `eb deploy --verbose` output before and after adding a new file in the directory?

**Comment by owurman** [comment]
If you want the full dump, let me know where to email it, but here's a
relevant bit:

INFO: Deploying code to <blah> in region us-west-2
INFO: Getting version label from git with git-describe
INFO: Found .ebignore, using system zip.
INFO: Zipping up folder at location: <blah>
INFO:   -skipping: ./analysis.log
INFO:   -skipping: ./.DS_Store
INFO:  +adding: .//
INFO:   +adding: ./ssh-production-bastion.sh
INFO:   +adding: ./requirements.txt
INFO:   -skipping: ./django_db.log
INFO:   -skipping: ./test.log
INFO:   +adding: ./jpad_bug_dump.sql
...

Note git status:
Untracked files:
  (use "git add <file>..." to include in what will be committed)
20201228_production_dump.sql
jpad_bug_dump.sql

So jpad_bug_dump.sql is getting added even though it's not checked in.

Now I ran it again, this time with staged (and not I haven't added ANY of
my changes to git yet, everything is still modified or untracked):
INFO: Deploying code to <blah> in region us-west-2
INFO: Getting version label from git with git-describe
INFO: Found .ebignore, using system zip.
INFO: Zipping up folder at location: <blah>
INFO:   -skipping: ./analysis.log
INFO:   -skipping: ./.DS_Store
INFO:  +adding: .//
INFO:   +adding: ./ssh-production-bastion.sh
INFO:   +adding: ./requirements.txt
INFO:   -skipping: ./django_db.log
INFO:   -skipping: ./test.log
INFO:   +adding: ./jpad_bug_dump.sql

Still there!

**Comment by Palakpatel67** [comment]
`--staged` command deploy files from the local git repository, where those files are not yet committed, but rather staged.

This is how I'm testing eb deploy stage functionality:
Here are my logs from running `eb deploy --verbose`.
```
Creating application version archive "app-1234”.
INFO: creating zip using git archive HEAD
INFO: git archive output: .ebextensions/
.ebextensions/logging.config
.gitignore
EBSampleApp-PHP.iml
index.php
INFO: Uploading archive to s3 location: app/app-1234.zip
```
I have added new file `scheduled.php` and staged it(not commited).
Output from running `git status`:
```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   scheduled.php 
```

After that run `eb deploy --staged --verbose`.
Logs:
```
Creating application version archive "app-12345”.
INFO: creating zip using git archive HEAD
INFO: git archive output: .ebextensions/
.ebextensions/logging.config
.gitignore
EBSampleApp-PHP.iml
index.php
scheduled.php
INFO: Uploading archive to s3 location: app/app-12345.zip
```

As you can see from above logs that `schedule.php` file is added when running `eb deploy` with `--staged`

**Comment by dgraver** [comment]
I am experiencing the same issue where an 'eb deploy' is deploying any files that have been modified, regardless if they are staged or not. This is relatively new as it wasn't occurring a month or so ago. Not sure if this has to do with the Mac OS upgrade to Big Sur or not.

> eb --version       
EB CLI 3.19.3 (Python 2.7.1)

Mac OS v11.1

**Comment by owurman** [comment]
I'm still on Catalina, so it's not Big Sur-specific.

**Comment by owurman** [comment]
@Palak I tried adding that dump file as in your case. It gets added even
without --staged:

eb deploy --verbose:
...
INFO:   +adding: ./jpad_bug_dump.sql

git status:

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
new file:   jpad_bug_dump.sql

So... obviously this behaves differently for you and me. What could be the
differences?

**Comment by Palakpatel67** [comment]
@owurman I see. `--staged` option is tightly coupled with `git stage` command. Could you tell me which git version you have?

**Comment by owurman** [comment]
git version 2.24.3 (Apple Git-128)

**Comment by dgraver** [comment]
Same git version for me also...

> git --version                                                                                                                                                     [01/25/21 12:33:33]
git version 2.24.3 (Apple Git-128)

**Comment by Palakpatel67** [comment]
Thanks for sending the information. 

In my case git version is : `git version 2.23.0`

This could be the issue with [apple git](https://www.atlassian.com/git/tutorials/install-git#mac-os-x:~:text=Apple%20actually%20maintain%20and%20ship%20their,using%20one%20of%20the%20methods%20below%3A). You have a version of Git from apple.
Unfortunately I don't have apple git installed on my computer to repro this issue. Could you try installing and using official version of git and see if this issue still persists?

**Comment by owurman** [comment]
That's really easier said than done. I'm not interested in messing up my
git environment for this, sorry.

**Comment by MHacker9404** [comment]
I'm seeing this same exact issue with git 2.34.1 on Windows - thought i was going nuts!

**Comment by NihalM99** [comment]
Hi @owurman  I've tested on Amazon Linux 2 with git version 2.42.0 and did not encounter the issue you described. The eb deploy --staged command behaved as expected, deploying only the staged changes and leaving the unstaged ones behind.
My directory structure : 
```
teststage1]$ ls -la
total 24
drwxr-xr-x 4 nihamukt amazon 4096 Oct 26 04:44 .
drwxr-xr-x 4 nihamukt amazon 4096 Oct 26 04:36 ..
drwxr-xr-x 2 nihamukt amazon 4096 Oct 26 04:45 .elasticbeanstalk
drwxr-xr-x 7 nihamukt amazon 4096 Oct 26 04:45 .git
-rw-r--r-- 1 nihamukt amazon  108 Oct 26 04:38 .gitignore
-rw-r--r-- 1 nihamukt amazon   60 Oct 26 04:44 index.html
```
index.html file before making changes : 
```
<h1>Hello, World!</h1>
~                                                                                                                                                                                                              
~                                                                                                                      
"index.html" 1L, 23B  
``` 
Committed these changes : 

```
teststage1]$ git commit -m "Initial commit"
[master (root-commit) ce85ba7] Initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 index.html
```
Did  `eb init ` to initialize my application 
Created an environment using ` eb create teststage1-env`
Made changes to index.html : 
```
<h1>Hello, World!</h1>
<h2>This is an unstaged change!</h2>
~
~
"index.html" 2L, 60B
```
Did `eb deploy --staged` 
```
teststage1]$ eb deploy --staged
Creating application version archive "app-ce85-231026_044505468793-stage-231026_044505468820".
Uploading teststage1/app-ce85-231026_044505468793-stage-231026_044505468820.zip to S3. This may take a while.
Upload Complete.
2023-10-26 04:45:06    INFO    Environment update is starting.      
2023-10-26 04:45:10    INFO    Deploying new version to instance(s).
```
Downloaded the latest application version from the Console and index.html did not not show the "This is an unstaged change!" text, it means the eb deploy --staged command is working as expected. The command respected the Git staging area and did not deploy changes that weren't staged. 


OS: Amazon Linux 2 
EBCLI-Version : 3.20.10 
Git version :2.42.0

**Comment by owurman** [comment]
This bug is so old that I'm not surprised if it's fixed by now. Sorry, but I'm past dealing with it. If it occurs again I can open a new issue.
