### ISSUE TITLE
Please release version 3.20.10

### ISSUE THREAD

**Issue by dennisjlee** [aws/aws-elastic-beanstalk-cli#489]
### Description

Version 3.20.10 has been mentioned in the changelog of this project as released on 9/15, but that version is not tagged in GitHub and is not available in PyPI. Please release it!

This version removes the dependency on docker-compose, which might help me resolve some dependency issues (we're running into [this issue](https://github.com/yaml/pyyaml/issues/601) when pip tries to install `PyYAML==5.4.1` with Python 3.11, and if we no longer had the `docker-compose` dependency we'd be able to resolve to `PyYAML==6.0.1`).

### Steps to reproduce

Searched PyPI and GitHub tags for 3.20.10

### Observed result

The version isn't published yet

### Expected result

To be able to access 3.20.10

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 22.04
2. EBCLI version: 3.20.9

**Comment by kirillrdy** [comment]
3.20.10 was released yesterday

**Comment by dennisjlee** [comment]
@kirillrdy thanks!
