### ISSUE TITLE
Six dependency not compatible with pip since early 2019

### ISSUE THREAD

**Issue by lee-hodg** [aws/aws-elastic-beanstalk-cli#49]
Since version 19.0 (2019-01-22) pip requires six>1.11, and yet awsebcli still needs a highly restrictive 'six>=1.11.0,<1.12.0'. This causes many issues such

```
ImportError: cannot import name 'ensure_str' from 'six'
```

When will awsebcli upgrade to a newer six?

**Comment by Palakpatel67** [comment]
Hey @fpghost, Thanks for reporting this issue. We will look into this and post any updates to this issue.

**Comment by Palakpatel67** [comment]
This ishould be fixed in awsebcli version [3.19.2](https://pypi.org/project/awsebcli/3.19.2/).
