### ISSUE TITLE
FEATURE: eb scale independently specify maximum and minimum

### ISSUE THREAD

**Issue by chammaaomar** [aws/aws-elastic-beanstalk-cli#51]
## Community Note

Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request. Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request. If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Tell us about your request
The `eb cli` offers the `scale` command. However, the scale command currently takes one numerical argument, and sets the maximum and minimum number of instances in the scaling group to the provided numerical argument. It hopefully isn't too hard to allow passing two numerical arguments, to allow specifying the maximum and minimum number of instances independently.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
I'm trying to automate the deployment of our backend, and I want to use the `awsebcli`. One of the steps involved in the deployment is to scale up our "staging" environment, since we're running a blue-green deployment scheme and want the "staging" environment to be ready to handle the load in case the production environment is having some issues post-deployment. However, when scaling up, we want to specify independent maximum and minimum thresholds, and that currently is impossible through the `awsebcli`.

### Are you currently working around this issue?
We're currently doing things manually, through the Elasticbeanstalk web interface / console. Thus, all the options are available.
### How are you currently solving this problem?
See above.

I can make a PR if you don't mind. Let me know.

**Comment by Mickeypeng** [comment]
@ chammaaomar  Thanks for requesting this feature.  eb scale command takes two positional argument now, the first is number of instance, and the second is environment name, which is optional. Therefore, if we add another argument to specify min and max independently, cli won't discriminate whether the second argument is max instance or is environment name. If we force user to specify min and max, that would break backward compatibility.
Therefore, we provide another way to specify both min and max in a programmatic way. Please see the latest document of eb config command, where we add a new option --update that allows customer to change multiple Options. In your case, you can modify MinSize and MaxSize option in aws:autoscaling:asg namespace.
