### ISSUE TITLE
Creating Auto Scaling launch configuration failed Reason: Resource handler returned message: "The Launch Configuration creation operation is not available in your account. Use launch templates to create configuration templates for your Auto Scaling groups. 

### ISSUE THREAD

**Issue by ivictbor** [aws/aws-elastic-beanstalk-cli#525]
Hey, this utility seams to be a good idea to deploy Dockerfile with couple of CLI commands. I wanted to us it for my blog post (I don't want readers to spend hours with creating EC2s or spawning ECS, just need som one-command to deploy Docker file). However I can't simply make it work, it always shows this:

### Description

I constantly get:

2024-10-07 08:43:19    ERROR   Creating Auto Scaling launch configuration failed Reason: Resource handler returned message: "The Launch Configuration creation operation is not available in your account. Use launch templates to create configuration templates for your Auto Scaling groups. (Service: AutoScaling, Status Code: 400, Request ID: cd860813-d8f8-4e9d-ab43-bb680d1c5da2)" (RequestToken: adc868f2-4f9a-a8aa-46d7-df6ab9df5c05, HandlerErrorCode: GeneralServiceException)
2024-10-07 08:43:35    INFO    Created target group named: arn:aws:elasticloadbalancing:eu-central-1:735356255780:targetgroup/awseb-AWSEB-5PXK7TDF8QUR/5b43a9e386255415

### Steps to reproduce

File Dockerrun.aws.json:

```
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "my-ai-blog",
    "Update": "true"
  },
  "Ports": [
    {
      "ContainerPort": 3500,
      "HostPort": 80
    }
  ],
  "Volumes": [
    {
      "HostDirectory": "/dbData",
      "ContainerDirectory": "/app/db"
    }
  ]
}
```

Then I run:

```
eb create live1 --instance-types t2.nano --max-instances 1
# eb create live1 --instance-types t2.nano --single # gives same error
```

### Observed result

ERROR   Creating Auto Scaling launch configuration failed Reason: Resource handler returned message: "The Launch Configuration creation operation is not available in your account. Use launch templates to create configuration templates for your Auto Scaling groups

### Expected result

Not to get error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: WIndows WSL
2. EBCLI version:

```
EB CLI 3.21.0 (Python 3.8.10 (default, Sep 11 2024, 16:02:53) 
[GCC 9.4.0])
```

Also tried latest form pip

**Comment by ivictbor** [comment]
Solved finally: I decided try to deploy by AWS UI Console and seen warning there about deprecating of Launch Configuration, after a reading I found that I was need to create folder `.ebextensions` and file `01-autoscaling.config`

```
option_settings:
  aws:autoscaling:launchconfiguration:
    DisableIMDSv1: true
```

Full example is here:  https://adminforth.dev/blog/ai-blog/#deploy-to-aws-elastic-beanstalk

Reccomendation to AWS team:
- Ideally would be nice not to create such in-obvious config and detect migration under the hood, this action raises entry level to AWS Beanstalk a lot!
- At least for now you can show deprecation warning in output of some (every?) `eb` command

**Comment by dcastillogi** [comment]
Hey @ivictbor!

More info on EB Launch Templates configuration here: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-autoscaling-launch-templates.html#environments-cfg-autoscaling-launch-templates-options

Thanks for the solution!
