### ISSUE TITLE
could not parse environment variables

### ISSUE THREAD

**Issue by shqear93** [aws/aws-elastic-beanstalk-cli#55]
### Description
environment command in beanstalk platform scripts does not work
Sorry for posting this here bug but I don't know where to report this

### Steps to reproduce
ssh to the beanstalk instance and execute the command
```
/opt/elasticbeanstalk/bin/get-config environment
```

### Observed result
```
could not parse environment variables
```

### Expected result
list of environment variables

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
1. OS: amzn2
2. it works using optionsettings command 
```
/opt/elasticbeanstalk/bin/get-config optionsettings
```
3. My environment variables: 
```
  "ANALYTICS_AWS_KEY": "",
  "ANALYTICS_AWS_REGION": "eu-west-1",
  "ANALYTICS_AWS_SECRET": "",
  "ANALYTICS_AWS_URL": "https://sqs.eu-west-1.amazonaws.com/********/awseb-**********",
  "ANALYTICS_ENABLED": "true",
  "ANALYTICS_SECRET_KEY": "*************",
  "APP_ADMIN_MAIL": "contact@******.com",
  "APP_DEBUG": "false",
  "APP_ENV": "local",
  "APP_KEY": "base64:xb/***********=",
  "APP_NAME": "Laravel",
  "APP_URL": "https://prod.core.******.com",
  "AWS_ACCESS_KEY_ID": "",
  "AWS_BUCKET": "",
  "AWS_DEFAULT_REGION": "eu-west-1",
  "AWS_SECRET_ACCESS_KEY": "",
  "BROADCAST_DRIVER": "log",
  "CACHE_DRIVER": "redis",
  "DB_CONNECTION": "mongodb",
  "DB_DATABASE": "******",
  "DB_DSN": "mongodb://*****:**(&**#**=***@*****:27017/*****?authSource=admin",
  "ELASTICSEARCH_HOST": "https://*****.eu-west-1.es.amazonaws.com:443",
  "ELASTICSEARCH_INDEX": "scout",
  "FILESYSTEM_DRIVER": "public",
  "FIREBASE_CREDENTIALS": "storage/********.json",
  "FIREBASE_ENABLE_DEBUG": "false",
  "FIREBASE_PROJECT": "******",
  "LOGGING_APP_TAG": "*******.logs",
  "LOGGING_NGINX_TAG": "*******.logs",
  "LOG_CHANNEL": "stack",
  "MAIL_ENCRYPTION": "tls",
  "MAIL_FROM_ADDRESS": "admin@********.com",
  "MAIL_FROM_NAME": "${APP_NAME}",
  "MAIL_HOST": "smtp.*******",
  "MAIL_MAILER": "smtp",
  "MAIL_PASSWORD": "********",
  "MAIL_PORT": "2525",
  "MAIL_USERNAME": "******",
  "MIX_PUSHER_APP_CLUSTER": "${PUSHER_APP_CLUSTER}",
  "MIX_PUSHER_APP_KEY": "${PUSHER_APP_KEY}",
  "PUSHER_APP_CLUSTER": "mt1",
  "PUSHER_APP_ID": "",
  "PUSHER_APP_KEY": "",
  "PUSHER_APP_SECRET": "",
  "QUEUE_CONNECTION": "redis",
  "REDIS_CLIENT": "predis",
  "REDIS_HOST": "***-prod.rodwzz.***",
  "REDIS_PASSWORD": null,
  "REDIS_PORT": "6379",
  "SCOUT_DRIVER": "elastic",
  "SCOUT_QUEUE": "true",
  "SESSION_DRIVER": "file",
  "SESSION_LIFETIME": "120"
```
4. Beanstalk Solution:
```
PHP 7.3 running on 64bit Amazon Linux 2/3.1.3
```

**Comment by Palakpatel67** [comment]
@shqear93 thanks for reporting this. Elastic Beanstalk currently don't support `get-config` for Linux 2 platforms but we do have a plan to support this. Same issue was reported on [elastic-beanstalk-sample](https://github.com/awsdocs/elastic-beanstalk-samples/issues/111) GitHub page.

**Comment by shqear93** [comment]
As a workaround I wrote this script :
```
/opt/elasticbeanstalk/bin/get-config optionsettings | \
    jq '."aws:elasticbeanstalk:application:environment"' | \
    jq -r 'to_entries | .[] | "export \(.key)=\"\(.value)\""'
```

**Comment by Palakpatel67** [comment]
thank you! Closing this issue, feel free to reopen it if you have any questions.

**Comment by realnsleo** [comment]
@shqear93, sorry for re-opening this. I am facing the same issue with `Docker running on 64bit Amazon Linux 2/3.2.6`. One of the scripts in my `.ebextenstions` folder requires access to an environment variable. How would you use the workaround script you posted above to access a variable in the script under `.ebextensions`. Thank you.

**Comment by jason-grayza** [comment]
commands:
    setvars:
        command: /opt/elasticbeanstalk/bin/get-config optionsettings | jq -r 'to_entries | .[] | "export \(.key)=\"\(.value)\""' > /etc/profile.d/sh.local
packages:
    yum:
        jq: []

**Comment by jason-grayza** [comment]
I ended up using the following to make all env variables avaialble system-wide. 

commands:
  setvars:
    command: /opt/elasticbeanstalk/bin/get-config optionsettings | jq '."aws:elasticbeanstalk:application:environment"' | jq -r 'to_entries | .[] | "\(.key)=\"\(.value)\""' > /etc/environment
packages:
  yum:
    jq: []

**Comment by AdamSelene** [comment]
I had a similar issue: `get-config environment` would fail on one Amazon Linux 2 environment ("could not parse environment variables"), but it was working on others (with different environment variables). 
Turns out `get-config environment` was choking on an env var that was set to `"null"` (i.e. the 4-characters string "null") - I updated it and it worked 🎉

**Comment by amman20** [comment]
Hey Friends I am still getting the error today.

Any change happened?

**Comment by lululombard** [comment]
Still getting this in 2024... Come on AWS fix your stuff.

**Comment by iliagu** [comment]
I Had the same issue on Linux 2023. 
I tried to create ELB through CLI based on the existing ELB config JSON. 
Turns out the JSON contained an option "EnvironmentVariables" with "aws:cloudformation:template:parameter" namespace, and it had all environment parameters aggregated into a single string.
When I removed it from the JSON it solved the issue and this option was created automatically in ELB creation process.

**Comment by SlyDave** [comment]
> I had a similar issue: `get-config environment` would fail on one Amazon Linux 2 environment ("could not parse environment variables"), but it was working on others (with different environment variables). Turns out `get-config environment` was choking on an env var that was set to `"null"` (i.e. the 4-characters string "null") - I updated it and it worked 🎉

Thanks, this was also my issue.

`/opt/elasticbeanstalk/bin/get-config environment`
> could not parse environment variables

`/opt/elasticbeanstalk/bin/get-config optionsettings | grep null`

>... "REDIS_PASSWORD":null ...

updated REDIS_PASSWORD TO empty string ''

`/opt/elasticbeanstalk/bin/get-config environment | grep null`
>  (blank)

`sudo /opt/elasticbeanstalk/bin/get-config environment -k APP_FAKER_LOCALE`
> en_GB 

All working now.

**Comment by martinamunoz** [comment]
> I Had the same issue on Linux 2023. I tried to create ELB through CLI based on the existing ELB config JSON. Turns out the JSON contained an option "EnvironmentVariables" with "aws:cloudformation:template:parameter" namespace, and it had all environment parameters aggregated into a single string. When I removed it from the JSON it solved the issue and this option was created automatically in ELB creation process based on parameters I have provided in the JSON.

This worked for me. Ive the same problem described here, and the solution worked like a charm. And I tried doing a rebuild and worked perfectly.
