### ISSUE TITLE
is docker-compose.yml not supported in AWS Elastic Beanstalk?

### ISSUE THREAD

**Issue by vitsensei** [aws/aws-elastic-beanstalk-cli#60]
Hi all,

In my root directory, I have my docker-compose.yml.

> $ ls

returns:

> build  cmd  docker-compose.yml  exp  go.mod  go.sum  LICENSE  media  pkg  README.md

In the same directory, I ran:

> $ eb init -p docker infogrid

> $ eb create infogridEnv

However, this gave me an error: 

>Instance deployment: Both 'Dockerfile' and 'Dockerrun.aws.json' are missing in your source bundle. Include at least one of them. The deployment failed.

The fact that it does not even include docker-compose.yml as the missing file makes me think it does not support docker-compose. This is contradicting with the [main documentation](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/docker.html) where it explicitly shows an example with docker-compose.yml.

**Comment by Palakpatel67** [comment]
@vitsensei thanks for reaching out. Elastic Beanstalk does support `docker-compose.yml`. I followed your repro steps and was able to successfully create EB environment. 

Could you provide `eb create --verbose` output?

**Comment by Palakpatel67** [comment]
Closing this issue as there has been no update for an extended period of time.

**Comment by Palisand** [comment]
If I may resuscitate this issue. I too am seeing the following error when attempting to deploy with `docker-compose.yml`:
> Instance deployment: Both 'Dockerfile' and 'Dockerrun.aws.json' are missing in your source bundle. Include at least one of them. The deployment failed.

I'm using the UI and uploading an archive with the following structure:
```
.
├── docker
│   └── Dockerfile
├── docker-compose.yml
└── src
```

My `docker-compose.yml` looks something like this:
```yml
version: "3.8"

services:

  project:
    build:
      context: .
      dockerfile: docker/Dockerfile
      ...

  nginx:
    ...
```

The error suggests the the compose file isn't being detected or that either `Dockerfile` or `Dockerrun.aws.json` is required at the root level of the archive, regardless of the presence of the compose file.

Is it not possible to supply an archive containing source files and `docker-compose.yml` *without* `Dockerfile` at its root? I want Docker Compose to perform the build.
