### ISSUE TITLE
the cli tool does not support your region in China

### ISSUE THREAD

**Issue by hkbluesky** [aws/aws-elastic-beanstalk-cli#65]
The cli tool does not support CodeCommit and beanstalk deployment for your region in Ningxia and Beijing, China. Please fix it ASAP. 

![image](https://user-images.githubusercontent.com/47656333/111168827-ce618780-8578-11eb-9cfa-d5de5aa9402b.png)

**Comment by Palakpatel67** [comment]
@hkbluesky thanks for reporting this issue. We will look into it and post any updates here. thanks!

**Comment by NihalM99** [comment]
Working in the Latest release . Please upgrade and try again . Please recheck the credentials file and confirm you are using the right credentials .
