### ISSUE TITLE
Ruby 3

### ISSUE THREAD

**Issue by interpegasus** [aws/aws-elastic-beanstalk-cli#67]
### Tell us about your request
What do you want us to build?

Hi, Ruby 3.0 brings some performance, concurrency, and _typing_ improvements among other advantages, and I would like to know if there are any plans to support it via AWS Beanstalk?

https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

### Additional context
https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.ruby

**Comment by Palakpatel67** [comment]
@interpegasus Thanks for reaching out. This would be the great addition for Elastic Beanstalk Ruby platforms. I would recommend posting your issue to [AWS Elastic Beanstalk Forums](https://forums.aws.amazon.com/forum.jspa?forumID=86) or [elastic-beanstalk-roadmap](https://github.com/aws/elastic-beanstalk-roadmap/issues) GitHub page and our platform team will pick it up from there. Closing as not related to EBCLI. thanks!

**Comment by interpegasus** [comment]
Thank you @Palakpatel67 Sounds good!
