### ISSUE TITLE
Nonsense output of `eb ssh` when env has 0 instances

### ISSUE THREAD

**Issue by spencerwilson** [aws/aws-elastic-beanstalk-cli#78]
### Description

When doing `eb ssh` into an EB env with no running instances:

```sh
% eb ssh my-env

Select an instance to ssh into
(default is 1): 1
Sorry, that is not a valid choice. Please choose a number between 1 and 0.
(default is 1): 0
Sorry, that is not a valid choice. Please choose a number between 1 and 0.
```

Expected behavior: Log a message like "There are no instances in environment ${env}" and exit nonzero.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 11.3
2. EBCLI version: 3.20.0

**Comment by Mickeypeng** [comment]
@spencerwilson Thanks for reporting this issue. We are working on it now.

**Comment by NihalM99** [comment]
@spencerwilson are you still facing the issue ? I launched an environment with EB-CLI v3.20.10 , deleted existing instances and tried to ssh into the environment now having 0 instances and I get an InvalidOptions error , which is expected . 
```
[nihamukt@dev-dsk-nihamukt-1e-a6573192 test2]$ eb ssh test2-ssh
ERROR: InvalidOptionsError - You tried to connect to an environment with no running instances.  SSH can only connect to running instances.  Use 'eb health' to display the status of instances in this environment.
```
OS : Amazon Linux 2 
EB-CLI : 3.20.10
