### ISSUE TITLE
Preventing multiple roles in AWS ebcli using python

### ISSUE THREAD

**Issue by josh-whit-me** [aws/aws-elastic-beanstalk-cli#86]
I have being trying to deploy my python project unto aws. I used `eb create --debug` so as to have a details of what is going on. The console told me I was not authorized.
On getting into aws i saw there were some errors in my log which were relating to roles 
These are
            1
```
"eventName":"AddRoleToInstanceProfile",
"errorCode":"LimitExceededException",
"errorMessage":"Cannot exceed quota for InstanceSessionsPerInstanceProfile: 1",
```

            2

```
"eventName":"CreateRole",
"errorCode":"EntityAlreadyExistsException",
"errorMessage":"Role already exists.",
```

		3
```
"eventName":"CreateInstanceProfile",
"errorCode":"EntityAlreadyExistsException",
"errorMessage":"Instance Profile already exists.",
```
I have being wondering 
1. Is there a way to determine if a role already exist since I did not programmatically create any role?
2. If a role already exist how I can update such a role?
3. How I can remove a role using `ebcli` while I am deploying the project?
4. How I can know all the roles that exist in my account from the ebcli?
Please fill out the sections below to help us address your issue.

**Comment by Mickeypeng** [comment]
Reply: Hi @josh-whit-me (https://github.com/josh-whit-me) thanks for reaching out. Unfortunately EB CLI can’t manage IAM roles: It will auto create aws-elasticbeanstalk-service-role and aws-elasticbeanstalk-ec2-role if they don’t exist, for details of these two roles, see our docs https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts-roles-service.html and  https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/iam-instanceprofile.html 
Other than creation, EB CLI don’t provide functions to manage or delete these two roles. If you want to delete or update them I recommend using IAM console, where you can see all roles created, update roles’ information, delete them, etc. See the below for our docs related to role management:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_manage_delete.html
In addition, we do have cli tool called awsebcli, which can also be used to manage roles. See below docs:
https://docs.aws.amazon.com/cli/latest/reference/iam/delete-role.html
https://docs.aws.amazon.com/cli/latest/reference/iam/list-roles.html
I hope this can answer your questions.
