### ISSUE TITLE
Please upgrade urllib3 dependency to avoid a security vulnerability

### ISSUE THREAD

**Issue by dennisjlee** [aws/aws-elastic-beanstalk-cli#88]
### Description

I installed awsebcli in a virtualenv and I have pinned my libraries into requirements.txt (via `pip freeze > requirements.txt`). 

My requirements.txt contains these two libraries as a result: 
```
awsebcli==3.20.1
urllib3==1.25.11
```

With this version of urllib3 installed, GitHub Dependabot gives a warning about a security vulnerability (https://github.com/advisories/GHSA-q2q7-5pp4-w6pg). The current dependency range for awsebcli is `urllib3>=1.25.4,<1.26`, which means that this dependency can't be satisfied. ([source](https://github.com/aws/aws-elastic-beanstalk-cli/blob/master/setup.py#L41))

In my case, this is not particularly serious because there is no workflow in which user input could be passed into urllib3, but that might not be the case for all users who use awsebcli. However, it is vexing that there is a Dependabot security vulnerability that I have to continue to ignore.

Can we update the setup.py for awsebcli to allow installing urllib3==1.26.5 or higher? That is the minimum version that no longer contains the vulnerability.

### Steps to reproduce

I am using Python 3.9.5 on Windows, using Git Bash - but the same problem should be reproducible on other platforms as well.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. EBCLI version: 3.20.1

**Comment by eytanhanig** [comment]
AWS' [Vulnerability Policy](https://aws.amazon.com/security/vulnerability-reporting/) states that "you will receive progress updates from AWS at least every five US working days". The failure of AWS to respond to this ticket is potentially a violation of their SLA.

**Comment by eytanhanig** [comment]
I've sent the following email to aws-security@amazon.com:

> The AWS Elastic Beanstalk open source tool requires that the Python package urllib3 be on the version 1.25.*. The security vulnerability [GHSA-q2q7-5pp4-w6pg](https://github.com/advisories/GHSA-q2q7-5pp4-w6pg), "Catastrophic backtracking in URL authority parser when passed URL containing many @ characters", was announced on June 1st. Fortunately a fix has been available starting with 1.26.5, which was released _before_ the security vulnerability announcement.
> 
> Please upgrade this dependency ASAP. Given that this vulnerability was flagged by GitHub's dependabot weeks ago and an [issue created in the GitHub project six days ago](https://github.com/aws/aws-elastic-beanstalk-cli/issues/88), please also provide the following:
> 
> 1. An explanation as to why this issue was not identified and fixed earlier.
> 2. A clear policy on whether [AWS' 5-day SLA for security vulnerabilities](https://aws.amazon.com/security/vulnerability-reporting/) applies to vulnerabilities raised on the issues pages of their open source projects.

**Comment by plygrnd** [comment]
@eytanhanig I'm with AWS Security - thanks for letting us know about this. I'll reply to your email.

To your comment above:

> AWS' Vulnerability Policy states that "you will receive progress updates from AWS at least every five US working days". The failure of AWS to respond to this ticket is potentially a violation of their SLA.

We don't use GitHub to manage security issue reports. If you discover or become aware of a potential security issue within any of AWS's open source offerings, please email aws-security@amazon.com.

**Comment by ibushong** [comment]
My suggestion is to use a separate virtualenv for deployment. In the majority of cases, your application itself shouldn't need awsebcli, so it doesn't really need to be in the same requirements file, and then you wont be bogged down by its dependency restrictions.

**Comment by eytanhanig** [comment]
@plygrnd Thanks for letting me know. I appreciate that aws-security@amazon.com is the canonical method for alerting AWS to security vulnerabilities, but IMO it's worth watching any unofficial communication channels that could alert the team to risks. Imagine if somebody tried to tell your CEO "Yes, it was on Twitter, but we held off acting until somebody sent us an email."

**Comment by dennisjlee** [comment]
Looks like this was resolved - thanks! 

https://github.com/aws/aws-elastic-beanstalk-cli/commit/eaea1712c5d70c15b8c1f040b3625182573dc7f1
