### ISSUE TITLE
Documentation unclear about behavior of eb config with regard to environment properties

### ISSUE THREAD

**Issue by dennisvang** [aws/aws-elastic-beanstalk-cli#92]
### Description

The [documentation for eb config](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-config.html) says:

> Note
>
> eb config doesn't **show** environment properties. To **set** environment properties that you can read from within your application, use eb setenv instead.

(my emphasis)

Indeed, `eb config some-env` or `eb config some-env --display` do not show environment properties.

However, when I call `eb config save` (using EB CLI 3.20.2 on Python 3.8.1), the saved configuration file **does** include all the environment properties. 

That obviously includes any **secrets** stored as environment properties.

Am I misinterpreting the note from the documentation?

EDIT:

I just confirmed that it *is* also possible to *set* environment properties using `eb config`, despite the note from the docs.

This can be done using `eb config --update "file://my-config.yml"` where the config file looks like:
```
OptionSettings:
  aws:elasticbeanstalk:application:environment:
    SOME_VAR: 'some value'

```

### Steps to reproduce

Run `eb config save`

### Observed result

Saved configuration file (YAML) includes environment properties.

### Expected result

Based on the documentation, I would expect the environment properties to be excluded from the configuration file.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: ubuntu
2. EBCLI version: EB CLI 3.20.2 on Python 3.8.1

**Comment by Mickeypeng** [comment]
Hi dennisvang@ thanks for reaching out! The command eb config does NOT show environment properties.  The same applies for eb config --display. The command eb config save does save environment properties to a local file. It saves the environment properties to a file because it is explicitly saving an application configuration (hence, eb config save).
