### ISSUE TITLE
YAML from "eb config save" fails parameter validation in "eb config --update"

### ISSUE THREAD

**Issue by dennisvang** [aws/aws-elastic-beanstalk-cli#95]
### Description

When trying to update an environment configuration using the YAML from a saved config file, the YAML fails parameter validation.

### Steps to reproduce

1. Create a clean web-server environment (named "temp3" in this case) running python 3.8 on Amazon Linux 2, with all default settings.
2. use `eb config save temp3` to save the configuration as YAML
3. edit the YAML file to remove all top-level sections *except* the `OptionSettings` section.
4. use `eb config temp3 --update "file://temp3-sc.cfg.yml"` to attempt an update of the configuration

### Observed result

```
ERROR: ValidationError - Parameter validation failed:
Invalid type for parameter OptionSettings[0].Value, value: False, type: <class 'bool'>, valid types: <class 'str'>
Invalid type for parameter OptionSettings[3].Value, value: {'Version': 1, 'CloudWatchMetrics': {'Instance': {'RootFilesystemUtil': None, 'CPUIrq': None, 'LoadAverage5min': None, 'ApplicationRequests5xx': None, 'ApplicationRequests4xx': None, 'CPUUser': None, 'LoadAverage1min': None, 'ApplicationLatencyP50': None, 'CPUIdle': None, 'InstanceHealth': None, 'ApplicationLatencyP95': None, 'ApplicationLatencyP85': None, 'ApplicationLatencyP90': None, 'CPUSystem': None, 'ApplicationLatencyP75': None, 'CPUSoftirq': None, 'ApplicationLatencyP10': None, 'ApplicationLatencyP99': None, 'ApplicationRequestsTotal': None, 'ApplicationLatencyP99.9': None, 'ApplicationRequests3xx': None, 'ApplicationRequests2xx': None, 'CPUIowait': None, 'CPUNice': None}, 'Environment': {'InstancesSevere': None, 'InstancesDegraded': None, 'ApplicationRequests5xx': None, 'ApplicationRequests4xx': None, 'ApplicationLatencyP50': None, 'ApplicationLatencyP95': None, 'ApplicationLatencyP85': None, 'InstancesUnknown': None, 'ApplicationLatencyP90': None, 'InstancesInfo': None, 'InstancesPending': None, 'ApplicationLatencyP75': None, 'ApplicationLatencyP10': None, 'ApplicationLatencyP99': None, 'ApplicationRequestsTotal': None, 'InstancesNoData': None, 'ApplicationLatencyP99.9': None, 'ApplicationRequests3xx': None, 'ApplicationRequests2xx': None, 'InstancesOk': None, 'InstancesWarning': None}}, 'Rules': {'Environment': {'ELB': {'ELBRequests4xx': {'Enabled': True}}, 'Application': {'ApplicationRequests4xx': {'Enabled': True}}}}}, type: <class 'dict'>, valid types: <class 'str'>
Invalid type for parameter OptionSettings[4].Value, value: True, type: <class 'bool'>, valid types: <class 'str'>
Invalid type for parameter OptionSettings[6].Value, value: True, type: <class 'bool'>, valid types: <class 'str'>

```
Apparently string values "false" and "true" are converted to booleans, but `eb config --update` expects strings.
Also, the `ConfigDocument` value is expanded by `eb config save`, but a string is required by `eb config --update`.

EDIT: 

YAML lists don't work either:
```yaml
...
  aws:autoscaling:launchconfiguration:
    SecurityGroups:
    - my-security-group
```
`Invalid type for parameter OptionSettings[19].Value, value: ['my-security-group'], type: <class 'list'>, valid types: <class 'str'>`
### Expected result

I expected the YAML returned by `eb config save` to be valid for use in `eb config --update`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: ubuntu
2. EBCLI version: EB CLI 3.20.2 (Python 3.8.1)

**Comment by Mickeypeng** [comment]
Hi dennisvang@, thanks for reaching out! Actually the the` eb config save` command and `eb config --update` command are working on two different concepts: The former one is used to save a saved configuration and the latter one is used to modify current environment configuration. Therefore the YAML files produced by the former command can’t be used by the latter one.
The latter command is developed because some customers want to modify current environment configuration programmatically. Usually these modifications are quite small so it’s not efficient to let customers input the whole environment configuration. Instead, they will only need to input the options they want to modify. For the exact format of `eb config --update`, here is our doc: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-config.html 
In addition, if you want to apply a saved configuration (i.e. the one you saved using eb config save), here is our doc: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-configuration-savedconfig.html

**Comment by dennisvang** [comment]
@Mickeypeng: Thanks for the explanation. Unfortunately the linked [documentation for eb config --update](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-config.html#eb3-configoptions) does *not* mention that the command only accepts a restricted subset of YAML. 

The output from `eb config --display`, on the other hand, does look like it could be used as input for `eb config --update`, as far as formatting is concerned. The problem there is that the output includes too many settings. 

Our use case is as follows: 

We would like to clone an environment from one platform branch (python 3.7 on AL2) to another platform branch (python 3.8 on AL2). This does not appear to be possible using the `eb clone` command or web console (we can only switch between versions in the same platform branch). For that reason, I am trying to copy *both* environment configuration *and* environment properties from the original py3.7 environment to a newly created py3.8 environment. Obviously we would like to automate this cloning process, to prevent human error and save time. AWS support confirmed that we should use `eb config` for this, but there does not seem to be a readily available command that makes this possible.

I can make it work by modifying a saved config, or by selecting specific lines from the `eb config --display` output, as described above, but that still requires human intervention. Perhaps there is better way? What would you suggest? The linked documentation is of no help in this respect.

**Comment by dennisvang** [comment]
@Mickeypeng: Another thing that is not clear to me from the documentation is why a saved configuration from `eb config save` does not incude all available option settings. Does it only include the customized settings (i.e. with non-default values)? Is this mentioned in the documentation somewhere?

I also noticed that `eb config save` includes environment properties in the saved config file (see issue #92), although in some cases it includes only a limited number of environment properties, skipping others.

It looks like `eb config --display` does return all settings, including default ones. Is that correct?
